#!/bin/sh
#
# @name RQ-7
#
# @type Plane A-Tail
# @class Plane
#
# @output Motor1 throttle
# @output Servo1 aileron left
# @output Servo2 aileron right
# @output Servo3 v-tail left
# @output Servo4 v-tail right
# @output Servo5 flaps
#
. ${R}etc/init.d/rc.fw_defaults

param set-default CA_AIRFRAME 1
param set-default CA_ROTOR_COUNT 1
param set-default CA_SV_CS_COUNT 5
